version: '3.10'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run dev
    networks:
      - ilias-rest-api_network  
    volumes:
      - .:/app
    working_dir: /app

networks:
  ilias-rest-api_network  :
    external: true  
