name: CI

on:
  push:
    branches:
      - master
      - feature/*
      - fix/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.5.0'

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check .

      - name: Run ESLint
        run: npx eslint .

      - name: Run tests
        run: npm test
